trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet pack --no-build --no-restore --configuration $(buildConfiguration)
  displayName: 'dotnet pack'

- publish: $(Build.SourcesDirectory)/.nupkg
  displayName: Publish artifacts
  artifact: packages